// Generated by Wrangler by running `wrangler types`

interface Env {
  OAUTH_KV: KVNamespace;
  GOOGLE_CLIENT_ID: string;
  GOOGLE_CLIENT_SECRET: string;
  COOKIE_ENCRYPTION_KEY: string;
  HOSTED_DOMAIN: string;
  ALLOWED_EMAILS?: string;
  ALLOWED_DOMAINS?: string;
  GADS_DEVELOPER_TOKEN: string;
  GADS_LOGIN_CUSTOMER_ID?: string;
  GADS_API_VERSION?: string;
  MCP_OBJECT: DurableObjectNamespace<import("./src/index").MyMCP>;
}
